name: ${project.artifactId}
main: ${project.groupId}.bukkit.Main
version: ${project.version}
author: TrollyLoki

depend: [FactCore]

api-version: 1.15

commands:
  friends:
    aliases: 'f'